#!/bin/bash
echo 'running the 1 script'
python3 /home/rortega/PycharmProjects/IronyMultiPyTorch/mainTrainCvMonoLing.py --batchsize 32  --epochs 50 --folds 10 --input /home/rortega/PycharmProjects/IronyMultiPyTorch/data/EsIroSvA19ES/training.tsv --language es --learning 5e-05 --lrdecay 1e-05 --lrstategy simple --maxlength 50 --minlearning 1e-05 --model beto --optimizer adam --output /home/rortega/PycharmProjects/IronyMultiPyTorch/output/EsIroSvA19ES --patience 15
echo 'running the 2 script'
python3 /home/rortega/PycharmProjects/IronyMultiPyTorch/mainTrainCvMonoLing.py --batchsize 32  --epochs 50 --folds 10 --input /home/rortega/PycharmProjects/IronyMultiPyTorch/data/EsIroSvA19ES/training.tsv --language es --learning 5e-05 --lrdecay 1e-05 --lrstategy dynamic --maxlength 50 --minlearning 1e-05 --model beto --optimizer adam --output /home/rortega/PycharmProjects/IronyMultiPyTorch/output/EsIroSvA19ES --patience 15
echo 'running the 3 script'
python3 /home/rortega/PycharmProjects/IronyMultiPyTorch/mainTrainCvMonoLing.py --batchsize 32  --epochs 50 --folds 10 --input /home/rortega/PycharmProjects/IronyMultiPyTorch/data/EsIroSvA19ES/training.tsv --language es --learning 5e-05 --lrdecay 1e-05 --lrstategy dynamic --maxlength 50 --minlearning 3e-05 --model beto --optimizer adam --output /home/rortega/PycharmProjects/IronyMultiPyTorch/output/EsIroSvA19ES --patience 15
echo 'running the 4 script'
python3 /home/rortega/PycharmProjects/IronyMultiPyTorch/mainTrainCvMonoLing.py --batchsize 32  --epochs 50 --folds 10 --input /home/rortega/PycharmProjects/IronyMultiPyTorch/data/EsIroSvA19ES/training.tsv --language es --learning 5e-05 --lrdecay 1e-05 --lrstategy simple --maxlength 50 --minlearning 1e-05 --model beto --optimizer rmsprop --output /home/rortega/PycharmProjects/IronyMultiPyTorch/output/EsIroSvA19ES --patience 15
echo 'running the 5 script'
python3 /home/rortega/PycharmProjects/IronyMultiPyTorch/mainTrainCvMonoLing.py --batchsize 32  --epochs 50 --folds 10 --input /home/rortega/PycharmProjects/IronyMultiPyTorch/data/EsIroSvA19ES/training.tsv --language es --learning 5e-05 --lrdecay 1e-05 --lrstategy dynamic --maxlength 50 --minlearning 1e-05 --model beto --optimizer rmsprop --output /home/rortega/PycharmProjects/IronyMultiPyTorch/output/EsIroSvA19ES --patience 15
echo 'running the 6 script'
python3 /home/rortega/PycharmProjects/IronyMultiPyTorch/mainTrainCvMonoLing.py --batchsize 32  --epochs 50 --folds 10 --input /home/rortega/PycharmProjects/IronyMultiPyTorch/data/EsIroSvA19ES/training.tsv --language es --learning 5e-05 --lrdecay 1e-05 --lrstategy dynamic --maxlength 50 --minlearning 3e-05 --model beto --optimizer rmsprop --output /home/rortega/PycharmProjects/IronyMultiPyTorch/output/EsIroSvA19ES --patience 15
echo 'running the 7 script'
python3 /home/rortega/PycharmProjects/IronyMultiPyTorch/mainTrainCvMonoLing.py --batchsize 32  --epochs 50 --folds 10 --input /home/rortega/PycharmProjects/IronyMultiPyTorch/data/EsIroSvA19ES/training.tsv --language es --learning 5e-05 --lrdecay 1e-05 --lrstategy simple --maxlength 50 --minlearning 1e-05 --model spanbert --optimizer adam --output /home/rortega/PycharmProjects/IronyMultiPyTorch/output/EsIroSvA19ES --patience 15
echo 'running the 8 script'
python3 /home/rortega/PycharmProjects/IronyMultiPyTorch/mainTrainCvMonoLing.py --batchsize 32  --epochs 50 --folds 10 --input /home/rortega/PycharmProjects/IronyMultiPyTorch/data/EsIroSvA19ES/training.tsv --language es --learning 5e-05 --lrdecay 1e-05 --lrstategy dynamic --maxlength 50 --minlearning 1e-05 --model spanbert --optimizer adam --output /home/rortega/PycharmProjects/IronyMultiPyTorch/output/EsIroSvA19ES --patience 15
echo 'running the 9 script'
python3 /home/rortega/PycharmProjects/IronyMultiPyTorch/mainTrainCvMonoLing.py --batchsize 32  --epochs 50 --folds 10 --input /home/rortega/PycharmProjects/IronyMultiPyTorch/data/EsIroSvA19ES/training.tsv --language es --learning 5e-05 --lrdecay 1e-05 --lrstategy dynamic --maxlength 50 --minlearning 3e-05 --model spanbert --optimizer adam --output /home/rortega/PycharmProjects/IronyMultiPyTorch/output/EsIroSvA19ES --patience 15
echo 'running the 10 script'
python3 /home/rortega/PycharmProjects/IronyMultiPyTorch/mainTrainCvMonoLing.py --batchsize 32  --epochs 50 --folds 10 --input /home/rortega/PycharmProjects/IronyMultiPyTorch/data/EsIroSvA19ES/training.tsv --language es --learning 5e-05 --lrdecay 1e-05 --lrstategy simple --maxlength 50 --minlearning 1e-05 --model spanbert --optimizer rmsprop --output /home/rortega/PycharmProjects/IronyMultiPyTorch/output/EsIroSvA19ES --patience 15
echo 'running the 11 script'
python3 /home/rortega/PycharmProjects/IronyMultiPyTorch/mainTrainCvMonoLing.py --batchsize 32  --epochs 50 --folds 10 --input /home/rortega/PycharmProjects/IronyMultiPyTorch/data/EsIroSvA19ES/training.tsv --language es --learning 5e-05 --lrdecay 1e-05 --lrstategy dynamic --maxlength 50 --minlearning 1e-05 --model spanbert --optimizer rmsprop --output /home/rortega/PycharmProjects/IronyMultiPyTorch/output/EsIroSvA19ES --patience 15
echo 'running the 12 script'
python3 /home/rortega/PycharmProjects/IronyMultiPyTorch/mainTrainCvMonoLing.py --batchsize 32  --epochs 50 --folds 10 --input /home/rortega/PycharmProjects/IronyMultiPyTorch/data/EsIroSvA19ES/training.tsv --language es --learning 5e-05 --lrdecay 1e-05 --lrstategy dynamic --maxlength 50 --minlearning 3e-05 --model spanbert --optimizer rmsprop --output /home/rortega/PycharmProjects/IronyMultiPyTorch/output/EsIroSvA19ES --patience 15
echo 'running the 13 script'
python3 /home/rortega/PycharmProjects/IronyMultiPyTorch/mainTrainCvMonoLing.py --batchsize 32  --epochs 50 --folds 10 --input /home/rortega/PycharmProjects/IronyMultiPyTorch/data/EsIroSvA19MX/training.tsv --language es --learning 5e-05 --lrdecay 1e-05 --lrstategy simple --maxlength 50 --minlearning 1e-05 --model beto --optimizer adam --output /home/rortega/PycharmProjects/IronyMultiPyTorch/output/EsIroSvA19MX --patience 15
echo 'running the 14 script'
python3 /home/rortega/PycharmProjects/IronyMultiPyTorch/mainTrainCvMonoLing.py --batchsize 32  --epochs 50 --folds 10 --input /home/rortega/PycharmProjects/IronyMultiPyTorch/data/EsIroSvA19MX/training.tsv --language es --learning 5e-05 --lrdecay 1e-05 --lrstategy dynamic --maxlength 50 --minlearning 1e-05 --model beto --optimizer adam --output /home/rortega/PycharmProjects/IronyMultiPyTorch/output/EsIroSvA19MX --patience 15
echo 'running the 15 script'
python3 /home/rortega/PycharmProjects/IronyMultiPyTorch/mainTrainCvMonoLing.py --batchsize 32  --epochs 50 --folds 10 --input /home/rortega/PycharmProjects/IronyMultiPyTorch/data/EsIroSvA19MX/training.tsv --language es --learning 5e-05 --lrdecay 1e-05 --lrstategy dynamic --maxlength 50 --minlearning 3e-05 --model beto --optimizer adam --output /home/rortega/PycharmProjects/IronyMultiPyTorch/output/EsIroSvA19MX --patience 15
echo 'running the 16 script'
python3 /home/rortega/PycharmProjects/IronyMultiPyTorch/mainTrainCvMonoLing.py --batchsize 32  --epochs 50 --folds 10 --input /home/rortega/PycharmProjects/IronyMultiPyTorch/data/EsIroSvA19MX/training.tsv --language es --learning 5e-05 --lrdecay 1e-05 --lrstategy simple --maxlength 50 --minlearning 1e-05 --model beto --optimizer rmsprop --output /home/rortega/PycharmProjects/IronyMultiPyTorch/output/EsIroSvA19MX --patience 15
echo 'running the 17 script'
python3 /home/rortega/PycharmProjects/IronyMultiPyTorch/mainTrainCvMonoLing.py --batchsize 32  --epochs 50 --folds 10 --input /home/rortega/PycharmProjects/IronyMultiPyTorch/data/EsIroSvA19MX/training.tsv --language es --learning 5e-05 --lrdecay 1e-05 --lrstategy dynamic --maxlength 50 --minlearning 1e-05 --model beto --optimizer rmsprop --output /home/rortega/PycharmProjects/IronyMultiPyTorch/output/EsIroSvA19MX --patience 15
echo 'running the 18 script'
python3 /home/rortega/PycharmProjects/IronyMultiPyTorch/mainTrainCvMonoLing.py --batchsize 32  --epochs 50 --folds 10 --input /home/rortega/PycharmProjects/IronyMultiPyTorch/data/EsIroSvA19MX/training.tsv --language es --learning 5e-05 --lrdecay 1e-05 --lrstategy dynamic --maxlength 50 --minlearning 3e-05 --model beto --optimizer rmsprop --output /home/rortega/PycharmProjects/IronyMultiPyTorch/output/EsIroSvA19MX --patience 15
echo 'running the 19 script'
python3 /home/rortega/PycharmProjects/IronyMultiPyTorch/mainTrainCvMonoLing.py --batchsize 32  --epochs 50 --folds 10 --input /home/rortega/PycharmProjects/IronyMultiPyTorch/data/EsIroSvA19MX/training.tsv --language es --learning 5e-05 --lrdecay 1e-05 --lrstategy simple --maxlength 50 --minlearning 1e-05 --model spanbert --optimizer adam --output /home/rortega/PycharmProjects/IronyMultiPyTorch/output/EsIroSvA19MX --patience 15
echo 'running the 20 script'
python3 /home/rortega/PycharmProjects/IronyMultiPyTorch/mainTrainCvMonoLing.py --batchsize 32  --epochs 50 --folds 10 --input /home/rortega/PycharmProjects/IronyMultiPyTorch/data/EsIroSvA19MX/training.tsv --language es --learning 5e-05 --lrdecay 1e-05 --lrstategy dynamic --maxlength 50 --minlearning 1e-05 --model spanbert --optimizer adam --output /home/rortega/PycharmProjects/IronyMultiPyTorch/output/EsIroSvA19MX --patience 15
echo 'running the 21 script'
python3 /home/rortega/PycharmProjects/IronyMultiPyTorch/mainTrainCvMonoLing.py --batchsize 32  --epochs 50 --folds 10 --input /home/rortega/PycharmProjects/IronyMultiPyTorch/data/EsIroSvA19MX/training.tsv --language es --learning 5e-05 --lrdecay 1e-05 --lrstategy dynamic --maxlength 50 --minlearning 3e-05 --model spanbert --optimizer adam --output /home/rortega/PycharmProjects/IronyMultiPyTorch/output/EsIroSvA19MX --patience 15
echo 'running the 22 script'
python3 /home/rortega/PycharmProjects/IronyMultiPyTorch/mainTrainCvMonoLing.py --batchsize 32  --epochs 50 --folds 10 --input /home/rortega/PycharmProjects/IronyMultiPyTorch/data/EsIroSvA19MX/training.tsv --language es --learning 5e-05 --lrdecay 1e-05 --lrstategy simple --maxlength 50 --minlearning 1e-05 --model spanbert --optimizer rmsprop --output /home/rortega/PycharmProjects/IronyMultiPyTorch/output/EsIroSvA19MX --patience 15
echo 'running the 23 script'
python3 /home/rortega/PycharmProjects/IronyMultiPyTorch/mainTrainCvMonoLing.py --batchsize 32  --epochs 50 --folds 10 --input /home/rortega/PycharmProjects/IronyMultiPyTorch/data/EsIroSvA19MX/training.tsv --language es --learning 5e-05 --lrdecay 1e-05 --lrstategy dynamic --maxlength 50 --minlearning 1e-05 --model spanbert --optimizer rmsprop --output /home/rortega/PycharmProjects/IronyMultiPyTorch/output/EsIroSvA19MX --patience 15
echo 'running the 24 script'
python3 /home/rortega/PycharmProjects/IronyMultiPyTorch/mainTrainCvMonoLing.py --batchsize 32  --epochs 50 --folds 10 --input /home/rortega/PycharmProjects/IronyMultiPyTorch/data/EsIroSvA19MX/training.tsv --language es --learning 5e-05 --lrdecay 1e-05 --lrstategy dynamic --maxlength 50 --minlearning 3e-05 --model spanbert --optimizer rmsprop --output /home/rortega/PycharmProjects/IronyMultiPyTorch/output/EsIroSvA19MX --patience 15
echo 'running the 25 script'
python3 /home/rortega/PycharmProjects/IronyMultiPyTorch/mainTrainCvMonoLing.py --batchsize 32  --epochs 50 --folds 10 --input /home/rortega/PycharmProjects/IronyMultiPyTorch/data/EsIroSvA19CU/training.tsv --language es --learning 5e-05 --lrdecay 1e-05 --lrstategy simple --maxlength 50 --minlearning 1e-05 --model beto --optimizer adam --output /home/rortega/PycharmProjects/IronyMultiPyTorch/output/EsIroSvA19CU --patience 15
echo 'running the 26 script'
python3 /home/rortega/PycharmProjects/IronyMultiPyTorch/mainTrainCvMonoLing.py --batchsize 32  --epochs 50 --folds 10 --input /home/rortega/PycharmProjects/IronyMultiPyTorch/data/EsIroSvA19CU/training.tsv --language es --learning 5e-05 --lrdecay 1e-05 --lrstategy dynamic --maxlength 50 --minlearning 1e-05 --model beto --optimizer adam --output /home/rortega/PycharmProjects/IronyMultiPyTorch/output/EsIroSvA19CU --patience 15
echo 'running the 27 script'
python3 /home/rortega/PycharmProjects/IronyMultiPyTorch/mainTrainCvMonoLing.py --batchsize 32  --epochs 50 --folds 10 --input /home/rortega/PycharmProjects/IronyMultiPyTorch/data/EsIroSvA19CU/training.tsv --language es --learning 5e-05 --lrdecay 1e-05 --lrstategy dynamic --maxlength 50 --minlearning 3e-05 --model beto --optimizer adam --output /home/rortega/PycharmProjects/IronyMultiPyTorch/output/EsIroSvA19CU --patience 15
echo 'running the 28 script'
python3 /home/rortega/PycharmProjects/IronyMultiPyTorch/mainTrainCvMonoLing.py --batchsize 32  --epochs 50 --folds 10 --input /home/rortega/PycharmProjects/IronyMultiPyTorch/data/EsIroSvA19CU/training.tsv --language es --learning 5e-05 --lrdecay 1e-05 --lrstategy simple --maxlength 50 --minlearning 1e-05 --model beto --optimizer rmsprop --output /home/rortega/PycharmProjects/IronyMultiPyTorch/output/EsIroSvA19CU --patience 15
echo 'running the 29 script'
python3 /home/rortega/PycharmProjects/IronyMultiPyTorch/mainTrainCvMonoLing.py --batchsize 32  --epochs 50 --folds 10 --input /home/rortega/PycharmProjects/IronyMultiPyTorch/data/EsIroSvA19CU/training.tsv --language es --learning 5e-05 --lrdecay 1e-05 --lrstategy dynamic --maxlength 50 --minlearning 1e-05 --model beto --optimizer rmsprop --output /home/rortega/PycharmProjects/IronyMultiPyTorch/output/EsIroSvA19CU --patience 15
echo 'running the 30 script'
python3 /home/rortega/PycharmProjects/IronyMultiPyTorch/mainTrainCvMonoLing.py --batchsize 32  --epochs 50 --folds 10 --input /home/rortega/PycharmProjects/IronyMultiPyTorch/data/EsIroSvA19CU/training.tsv --language es --learning 5e-05 --lrdecay 1e-05 --lrstategy dynamic --maxlength 50 --minlearning 3e-05 --model beto --optimizer rmsprop --output /home/rortega/PycharmProjects/IronyMultiPyTorch/output/EsIroSvA19CU --patience 15
echo 'running the 31 script'
python3 /home/rortega/PycharmProjects/IronyMultiPyTorch/mainTrainCvMonoLing.py --batchsize 32  --epochs 50 --folds 10 --input /home/rortega/PycharmProjects/IronyMultiPyTorch/data/EsIroSvA19CU/training.tsv --language es --learning 5e-05 --lrdecay 1e-05 --lrstategy simple --maxlength 50 --minlearning 1e-05 --model spanbert --optimizer adam --output /home/rortega/PycharmProjects/IronyMultiPyTorch/output/EsIroSvA19CU --patience 15
echo 'running the 32 script'
python3 /home/rortega/PycharmProjects/IronyMultiPyTorch/mainTrainCvMonoLing.py --batchsize 32  --epochs 50 --folds 10 --input /home/rortega/PycharmProjects/IronyMultiPyTorch/data/EsIroSvA19CU/training.tsv --language es --learning 5e-05 --lrdecay 1e-05 --lrstategy dynamic --maxlength 50 --minlearning 1e-05 --model spanbert --optimizer adam --output /home/rortega/PycharmProjects/IronyMultiPyTorch/output/EsIroSvA19CU --patience 15
echo 'running the 33 script'
python3 /home/rortega/PycharmProjects/IronyMultiPyTorch/mainTrainCvMonoLing.py --batchsize 32  --epochs 50 --folds 10 --input /home/rortega/PycharmProjects/IronyMultiPyTorch/data/EsIroSvA19CU/training.tsv --language es --learning 5e-05 --lrdecay 1e-05 --lrstategy dynamic --maxlength 50 --minlearning 3e-05 --model spanbert --optimizer adam --output /home/rortega/PycharmProjects/IronyMultiPyTorch/output/EsIroSvA19CU --patience 15
echo 'running the 34 script'
python3 /home/rortega/PycharmProjects/IronyMultiPyTorch/mainTrainCvMonoLing.py --batchsize 32  --epochs 50 --folds 10 --input /home/rortega/PycharmProjects/IronyMultiPyTorch/data/EsIroSvA19CU/training.tsv --language es --learning 5e-05 --lrdecay 1e-05 --lrstategy simple --maxlength 50 --minlearning 1e-05 --model spanbert --optimizer rmsprop --output /home/rortega/PycharmProjects/IronyMultiPyTorch/output/EsIroSvA19CU --patience 15
echo 'running the 35 script'
python3 /home/rortega/PycharmProjects/IronyMultiPyTorch/mainTrainCvMonoLing.py --batchsize 32  --epochs 50 --folds 10 --input /home/rortega/PycharmProjects/IronyMultiPyTorch/data/EsIroSvA19CU/training.tsv --language es --learning 5e-05 --lrdecay 1e-05 --lrstategy dynamic --maxlength 50 --minlearning 1e-05 --model spanbert --optimizer rmsprop --output /home/rortega/PycharmProjects/IronyMultiPyTorch/output/EsIroSvA19CU --patience 15
echo 'running the 36 script'
python3 /home/rortega/PycharmProjects/IronyMultiPyTorch/mainTrainCvMonoLing.py --batchsize 32  --epochs 50 --folds 10 --input /home/rortega/PycharmProjects/IronyMultiPyTorch/data/EsIroSvA19CU/training.tsv --language es --learning 5e-05 --lrdecay 1e-05 --lrstategy dynamic --maxlength 50 --minlearning 3e-05 --model spanbert --optimizer rmsprop --output /home/rortega/PycharmProjects/IronyMultiPyTorch/output/EsIroSvA19CU --patience 15
echo 'running the 37 script'
python3 /home/rortega/PycharmProjects/IronyMultiPyTorch/mainTrainCvMonoLing.py --batchsize 32  --epochs 50 --folds 10 --input /home/rortega/PycharmProjects/IronyMultiPyTorch/data/EsIroSvA19/training.tsv --language es --learning 5e-05 --lrdecay 1e-05 --lrstategy simple --maxlength 50 --minlearning 1e-05 --model beto --optimizer adam --output /home/rortega/PycharmProjects/IronyMultiPyTorch/output/EsIroSvA19 --patience 15
echo 'running the 38 script'
python3 /home/rortega/PycharmProjects/IronyMultiPyTorch/mainTrainCvMonoLing.py --batchsize 32  --epochs 50 --folds 10 --input /home/rortega/PycharmProjects/IronyMultiPyTorch/data/EsIroSvA19/training.tsv --language es --learning 5e-05 --lrdecay 1e-05 --lrstategy dynamic --maxlength 50 --minlearning 1e-05 --model beto --optimizer adam --output /home/rortega/PycharmProjects/IronyMultiPyTorch/output/EsIroSvA19 --patience 15
echo 'running the 39 script'
python3 /home/rortega/PycharmProjects/IronyMultiPyTorch/mainTrainCvMonoLing.py --batchsize 32  --epochs 50 --folds 10 --input /home/rortega/PycharmProjects/IronyMultiPyTorch/data/EsIroSvA19/training.tsv --language es --learning 5e-05 --lrdecay 1e-05 --lrstategy dynamic --maxlength 50 --minlearning 3e-05 --model beto --optimizer adam --output /home/rortega/PycharmProjects/IronyMultiPyTorch/output/EsIroSvA19 --patience 15
echo 'running the 40 script'
python3 /home/rortega/PycharmProjects/IronyMultiPyTorch/mainTrainCvMonoLing.py --batchsize 32  --epochs 50 --folds 10 --input /home/rortega/PycharmProjects/IronyMultiPyTorch/data/EsIroSvA19/training.tsv --language es --learning 5e-05 --lrdecay 1e-05 --lrstategy simple --maxlength 50 --minlearning 1e-05 --model beto --optimizer rmsprop --output /home/rortega/PycharmProjects/IronyMultiPyTorch/output/EsIroSvA19 --patience 15
echo 'running the 41 script'
python3 /home/rortega/PycharmProjects/IronyMultiPyTorch/mainTrainCvMonoLing.py --batchsize 32  --epochs 50 --folds 10 --input /home/rortega/PycharmProjects/IronyMultiPyTorch/data/EsIroSvA19/training.tsv --language es --learning 5e-05 --lrdecay 1e-05 --lrstategy dynamic --maxlength 50 --minlearning 1e-05 --model beto --optimizer rmsprop --output /home/rortega/PycharmProjects/IronyMultiPyTorch/output/EsIroSvA19 --patience 15
echo 'running the 42 script'
python3 /home/rortega/PycharmProjects/IronyMultiPyTorch/mainTrainCvMonoLing.py --batchsize 32  --epochs 50 --folds 10 --input /home/rortega/PycharmProjects/IronyMultiPyTorch/data/EsIroSvA19/training.tsv --language es --learning 5e-05 --lrdecay 1e-05 --lrstategy dynamic --maxlength 50 --minlearning 3e-05 --model beto --optimizer rmsprop --output /home/rortega/PycharmProjects/IronyMultiPyTorch/output/EsIroSvA19 --patience 15
echo 'running the 43 script'
python3 /home/rortega/PycharmProjects/IronyMultiPyTorch/mainTrainCvMonoLing.py --batchsize 32  --epochs 50 --folds 10 --input /home/rortega/PycharmProjects/IronyMultiPyTorch/data/EsIroSvA19/training.tsv --language es --learning 5e-05 --lrdecay 1e-05 --lrstategy simple --maxlength 50 --minlearning 1e-05 --model spanbert --optimizer adam --output /home/rortega/PycharmProjects/IronyMultiPyTorch/output/EsIroSvA19 --patience 15
echo 'running the 44 script'
python3 /home/rortega/PycharmProjects/IronyMultiPyTorch/mainTrainCvMonoLing.py --batchsize 32  --epochs 50 --folds 10 --input /home/rortega/PycharmProjects/IronyMultiPyTorch/data/EsIroSvA19/training.tsv --language es --learning 5e-05 --lrdecay 1e-05 --lrstategy dynamic --maxlength 50 --minlearning 1e-05 --model spanbert --optimizer adam --output /home/rortega/PycharmProjects/IronyMultiPyTorch/output/EsIroSvA19 --patience 15
echo 'running the 45 script'
python3 /home/rortega/PycharmProjects/IronyMultiPyTorch/mainTrainCvMonoLing.py --batchsize 32  --epochs 50 --folds 10 --input /home/rortega/PycharmProjects/IronyMultiPyTorch/data/EsIroSvA19/training.tsv --language es --learning 5e-05 --lrdecay 1e-05 --lrstategy dynamic --maxlength 50 --minlearning 3e-05 --model spanbert --optimizer adam --output /home/rortega/PycharmProjects/IronyMultiPyTorch/output/EsIroSvA19 --patience 15
echo 'running the 46 script'
python3 /home/rortega/PycharmProjects/IronyMultiPyTorch/mainTrainCvMonoLing.py --batchsize 32  --epochs 50 --folds 10 --input /home/rortega/PycharmProjects/IronyMultiPyTorch/data/EsIroSvA19/training.tsv --language es --learning 5e-05 --lrdecay 1e-05 --lrstategy simple --maxlength 50 --minlearning 1e-05 --model spanbert --optimizer rmsprop --output /home/rortega/PycharmProjects/IronyMultiPyTorch/output/EsIroSvA19 --patience 15
echo 'running the 47 script'
python3 /home/rortega/PycharmProjects/IronyMultiPyTorch/mainTrainCvMonoLing.py --batchsize 32  --epochs 50 --folds 10 --input /home/rortega/PycharmProjects/IronyMultiPyTorch/data/EsIroSvA19/training.tsv --language es --learning 5e-05 --lrdecay 1e-05 --lrstategy dynamic --maxlength 50 --minlearning 1e-05 --model spanbert --optimizer rmsprop --output /home/rortega/PycharmProjects/IronyMultiPyTorch/output/EsIroSvA19 --patience 15
echo 'running the 48 script'
python3 /home/rortega/PycharmProjects/IronyMultiPyTorch/mainTrainCvMonoLing.py --batchsize 32  --epochs 50 --folds 10 --input /home/rortega/PycharmProjects/IronyMultiPyTorch/data/EsIroSvA19/training.tsv --language es --learning 5e-05 --lrdecay 1e-05 --lrstategy dynamic --maxlength 50 --minlearning 3e-05 --model spanbert --optimizer rmsprop --output /home/rortega/PycharmProjects/IronyMultiPyTorch/output/EsIroSvA19 --patience 15
